### ISSUE TITLE
FW2.121.5 - PCB Temperature 

### ISSUE THREAD

**Issue by achgut** [achgut/Modbus_Versicharge#17]
Fehler: Temp ist jetzt ~8°C - 10°C zu tief

**Comment by coolo** [comment]
das kommt leider so von den Hardware-Sensoren. Wir hatten im Parkhaus auch angeblich 17 Grad auf dem PCB. Bei 34 Grad im Schatten.

**Comment by achgut** [comment]
Wert heute bei FW2.128 könnte wieder stimmen. Es sind 12Grad draussen:
![image](https://github.com/achgut/Modbus_Versicharge/assets/114326418/a5d6f280-f98b-4706-b156-1c46f6c98cfe)

Muss weiter beobachtet werden.
