### ISSUE TITLE
FW2.128: Pause Register 1629 nicht mehr vorhanden

### ISSUE THREAD

**Issue by achgut** [achgut/Modbus_Versicharge#18]
Ein wichtiges Register 1629 (Pause) ist bei der neuen FW Version verschwunden. Dadurch funktioniert die Ladesteuerung mit PV Überschussladen nicht mehr. Das Register 1629 wurde für das Starten und Stoppen des Ladevorgangs verwendet, wenn Überschuss vorhanden ist.
 
In den Release Notes habe ich noch folgendes gelesen:
•	VERCHGTL-694 Pause command removed from Modbus register map, simplify smart charging

Finde aber kein anderes Register, worüber diese Steuerung machbar wäre. Modbus Map in der Anlage. 
[versicharge_wallbox_modBus_map_en-US (5).pdf](https://github.com/achgut/Modbus_Versicharge/files/12257584/versicharge_wallbox_modBus_map_en-US.5.pdf)

Ticket eröffnet, warte auf Antwort

**Comment by achgut** [comment]
Feedback Technical Assistance:
Pause Register nicht mehr zu verwenden. Steuerung über MaxCurrent Register.
MaxCurrent = 0 -> Pause
MaxCurrent != 0 -> keine Pause

**Comment by coolo** [comment]
Korrekt muss es heißen: <6 -> Pause, >=6 -> keine Pause.
